<h1 align="center">Сингулярное разложение матриц</h1>

In [1]:
import numpy as np
from math import sqrt
np.set_printoptions(precision=2, suppress=True)

1. Найдите посредством NumPy SVD для матрицы:

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}$$


In [2]:
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])

In [3]:
U, s, W = np.linalg.svd(A)

In [4]:
V = W.T

D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [5]:
for key, value in dict(U=U, D=D, V=V).items():
    print(f"Матрица {key}:\n{value}\n")

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]

Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]



In [6]:
print(f"Матрица A:\n{np.dot(np.dot(U, D), V.T)}")

Матрица A:
[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1.  0.]]


2. Для матрицы из предыдущего задания найдите:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [7]:
print(f"Евклидова норма: {max(s)};\nнорма Фробениуса: {sqrt(sum(list(map(lambda x: x ** 2, list(s)))))}")

Евклидова норма: 8.824868854820442;
норма Фробениуса: 11.045361017187261
