<h1 align="center">Матрицы и матричные операции</h1>

In [1]:
import numpy as np

### Часть 1

1. Установите, какие произведения матриц $AB$ и $BA$ определены, и найдите размерности полученных матриц:

а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

а) Матрицы $AB$ и $BA$ не определены;
    
б) Матрица $AB$ с размерностью $2\times 3$ определена, матрица $BA$ не определена;
    
в) Матрицы $AB$ с размерностью $8\times 8$ и $BA$ с размерностью $3\times 3$ определены;
    
г) Матрицы $AB$ и $BA$ определены с размерностью $4\times 4$.

2. Найдите сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$$ A+B=\begin{pmatrix}
1+4 & -2-1\\ 
3+0 & 0+5
\end{pmatrix}=\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$$

$$ A*B=\begin{pmatrix}
1*4 & 1*(-1)-2*5\\ 
3*4 & 3*(-1)
\end{pmatrix}=\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$$

$$ B*A=\begin{pmatrix}
4*1-1*3 & 4*(-2)\\ 
5*3 & 0
\end{pmatrix}=\begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}$$

In [2]:
A, B = np.array([[1, -2], [3, 0]]), np.array([[4, -1], [0, 5]])
print(A, B, sep="\n\n")

[[ 1 -2]
 [ 3  0]]

[[ 4 -1]
 [ 0  5]]


In [3]:
print(f"Сумма матриц A и B:\n{A+B}")

Сумма матриц A и B:
[[ 5 -3]
 [ 3  5]]


In [4]:
print(f"Произведение матриц A*B:\n{A.dot(B)}")

Произведение матриц A*B:
[[  4 -11]
 [ 12  -3]]


In [5]:
print(f"Произведение матриц B*A:\n{B.dot(A)}")

Произведение матриц B*A:
[[ 1 -8]
 [15  0]]


3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$$ 3A−2B+4C = 3*\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}-2*\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}+4*\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = \begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}+\begin{pmatrix}
0 & -10\\ 
-4 & 2
\end{pmatrix}+\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} = \begin{pmatrix}
3+8 & 21-10-16\\ 
9-4+4 & -18+2+4
\end{pmatrix}=\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$$

In [6]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

3*A - 2*B + 4*C 

array([[ 11,  -5],
       [  9, -12]])

4. Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислите $AA^{T}$ и $A^{T}A$

$$ A^T=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$$

In [7]:
matrix = np.array([[4, 1], [5, -2], [2, 3]])
matrix.T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

$$ A*A^T=\begin{pmatrix}
4*4+1 & 4*5-2 & 2*4+3 \\ 
5*4-2 & 5*5-2*(-2) & 2*5+3*(-2) \\
2*4+3 & 2*5+3*(-2) & 2*2+3*3
\end{pmatrix}=\begin{pmatrix}
17 & 18 & 11 \\ 
18 & 29 & 4 \\
11 & 4 & 13
\end{pmatrix}$$

In [8]:
np.dot(matrix, matrix.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

$$ A^T*A=\begin{pmatrix}
4*4+5*5+2*2 & 4+5*(-2)+2*3 \\ 
4-2*5+3*2 & 1-2*(-2)+3*3
\end{pmatrix}=\begin{pmatrix}
45 & 0 \\ 
0 & 14
\end{pmatrix}$$

In [9]:
np.dot(matrix.T, matrix)

array([[45,  0],
       [ 0, 14]])

5*. Напишите на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [10]:
def matrices_product(A, B, order=False):
    '''Returns the result of multiplying matrix `A` by `B`,
    the TRUE value of the `order` parameter changes the order of multiplication.'''
    if order:
        A, B = B, A
    if len(A[0]) == len(B):
        AB = [[0 for m in range(len(B[0]))] for n in range(len(A))]
        B_transposed = [[B[m][n] for m in range(len(B))] for n in range(len(B[0]))]
        for index_1, i in enumerate(A):
            for index_2, j in enumerate(B_transposed):
                AB[index_1][index_2] = sum([x*y for (x, y) in zip(i, j)])
        return AB
    else:
        return "Матрицы с такими размерностями нельзя перемножить!"

In [11]:
C, D = np.random.randint(10, size=(2, 3)), np.random.randint(25, size=(2, 2))
print(C, D, sep="\n\n")

[[5 2 8]
 [1 7 6]]

[[15  0]
 [ 4  2]]


In [12]:
print(matrices_product(C, D))

Матрицы с такими размерностями нельзя перемножить!


In [13]:
print(matrices_product(C, D, True))

[[75, 30, 120], [22, 22, 44]]


In [14]:
D.dot(C)

array([[ 75,  30, 120],
       [ 22,  22,  44]])

### Часть 2

1. Вычислите определитель:

a)

$$A=\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}$$

$$ detA = sinx * sinx - (-cosx)*cosx = sin^2x+cos^2x = 1$$ 

б)
    
$$B=\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}$$

$$ detB = 9 * \begin{vmatrix}
4 & 2 \\ 
0 & 5
\end{vmatrix} = 9 * 4 * 5= 180$$ 

In [15]:
matrix_B = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
np.linalg.det(matrix_B)

180.0

в)

$$C=\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}$$

$ detC = 1*\begin{vmatrix}
5 & 6 \\ 
8 & 9
\end{vmatrix} - 2*\begin{vmatrix}
4 & 6 \\ 
7 & 9
\end{vmatrix} + 3*\begin{vmatrix}
4 & 5 \\ 
7 & 8
\end{vmatrix} = 5*9 - 8*6-2*(4*9-7*6)+3*(4*8-7*5) = 45-48-2*(36-42)+3*(32-35)=-3+12-9 = 0$

In [16]:
matrix_C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
int(np.linalg.det(matrix_C))

0

2. Определитель матрицы $A$ равен $4$. Найдите:

   а) $det(A^{2}) = det(AA) = detA * detA = 4*4 = 16$;
    
   б) $det(A^{T}) = detA = 4$;
    
   в) $det(2A) = 2^m *detA = 2^m * 4 = 2^{m+2},\ где\ m-\ количество\ строк/столбцов\ в\ матрице$

3.  Докажите, что матрица:

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Согласно одному из свойств определителей, если две строки (столбца) матрицы линейно зависимы, то определитель этой матрицы равен нулю. В данном случае линейно зависимыми являются 1 и 2 строки:<br />
$ -2*(-2\ 7\ -3) = (4\ -14\ 6)$

In [17]:
matrix = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
np.linalg.det(matrix)

0.0

4. Найдите ранг матрицы:

а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}=>\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix}=>\begin{pmatrix}
1 & 1 & 1\\ 
1 & 2 & 3
\end{pmatrix}=>\begin{pmatrix}
1 & 1 & 1\\ 
0 & 1 & 2
\end{pmatrix}=>Ранг\ матрицы\ равен\ 2$

In [18]:
matrix_A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
np.linalg.matrix_rank(matrix_A)

2

б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}=>\begin{pmatrix}
2 & 3 & 5 & 6\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
0 & 0 & 2 & 1
\end{pmatrix}=>\begin{pmatrix}
1 & 1.5 & 2.5 & 3\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
0 & 0 & 2 & 1
\end{pmatrix}=>\begin{pmatrix}
1 & 1.5 & 2.5 & 3\\ 
0 & 0 & 1 & 1\\ 
0 & 0 & 4 & 3\\ 
0 & 0 & 2 & 1
\end{pmatrix}=>\begin{pmatrix}
1 & 1.5 & 2.5 & 3\\ 
0 & 0 & 1 & 1\\ 
0 & 0 & 0 & -1\\ 
0 & 0 & 0 & -1
\end{pmatrix}=>$

$\begin{pmatrix}
1 & 1.5 & 2.5 & 3\\ 
0 & 0 & 1 & 1\\ 
0 & 0 & 0 & 1\\ 
0 & 0 & 0 & -1
\end{pmatrix}=>\begin{pmatrix}
1 & 1.5 & 2.5 & 3\\ 
0 & 0 & 1 & 1\\ 
0 & 0 & 0 & 1\\ 
0 & 0 & 0 & 0
\end{pmatrix}=>Ранг\ матрицы\ равен\ 3$

In [19]:
matrix_B = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
np.linalg.matrix_rank(matrix_B)

3