<h1 align="center">Системы линейных уравнений</h1>

In [1]:
import numpy as np
from scipy import linalg

In [2]:
def is_matrix_degenerate(matrix):
    return f"{'Матрица коэффициентов невырождена' if np.linalg.det(matrix) !=0 else 'Матрица коэффициентов вырождена'}, " \
            f"так как определелитель равен {np.linalg.det(matrix)}"

### Часть 1

1. Решите систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$
Представим СЛАУ в матричной форме:
$$ 
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}
$$
Применим преобразования:
$$
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & -1 & 1 & 5\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}
$$
Полученная матрица соответствует системе:
$$
\begin{cases}
x_1+x_2-x_3-2x_4=0, \\
~~~-x_2+x_3+5x_4=-2, \\
~~~~~~~-2x_3+3x_4=4
\end{cases}=>
\begin{cases}
x_1=2x_4+x_3-x_2, \\
x_2=2+x_3+5x_4, \\
x_3=1.5x_4-2
\end{cases}
$$
У исходной СЛАУ есть общее решение при $x_4=const$:
\begin{cases}
x_4 = k, \\
x_3=1.5k-2, \\
x_2=6.5k, \\
x_1=-3k-2
\end{cases}

2. Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений:

а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$<br/>

Число уравнений равно числу неизвестных.

In [3]:
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
print(is_matrix_degenerate(A))

Матрица коэффициентов невырождена, так как определелитель равен 32.0


Перепишем эту систему в векторном виде:

$ 
x_{1}\begin{pmatrix}
3\\2\\1
\end{pmatrix}+
x_{2}\begin{pmatrix}
-1\\-5\\1
\end{pmatrix}+
x_{3}\begin{pmatrix}
1\\-3\\-1
\end{pmatrix}=
\begin{pmatrix}
4\\-17\\0
\end{pmatrix}
$

Векторы столбцов коэффициентов $𝑎_1,𝑎_2,𝑎_3$  линейно независимы, => такая система совместна, и её решение единственно.

б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$<br/>

Число уравнений равно числу неизвестных.

In [4]:
B = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
print(is_matrix_degenerate(B))

Матрица коэффициентов вырождена, так как определелитель равен 0.0


СЛАУ является несовместной.

в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$<br/>

Число уравнений меньше числа неизвестных.<br/>
Перепишем эту систему в векторном виде:

$ 
x_{1}\begin{pmatrix}
1\\3
\end{pmatrix}+
x_{2}\begin{pmatrix}
2\\1
\end{pmatrix}+
x_{3}\begin{pmatrix}
5\\-8
\end{pmatrix}=
\begin{pmatrix}
4\\-2
\end{pmatrix}
$

Данная СЛАУ совместная и неопределенная.

3. Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}$$

In [5]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
b = np.array([[3, 2, 4, 1]])
print(A, b.transpose(), sep="\n\n")

[[ 1  3 -2  4]
 [ 0  5  0  1]
 [ 0  0  3  0]
 [ 0  0  0  2]]

[[3]
 [2]
 [4]
 [1]]


In [6]:
A_expanded = np.append(A, b.T, axis=1)
print(A_expanded)

[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]


In [7]:
np.linalg.matrix_rank(A) == np.linalg.matrix_rank(A_expanded) == 4

True

In [8]:
print(f"Система линейных уравнений имеет единственное решение:",  
      f"{', '.join([f'x_{index+1} = {x}' for index, x in enumerate(np.linalg.solve(A, b[0]))])}")

Система линейных уравнений имеет единственное решение: x_1 = 2.7666666666666666, x_2 = 0.3, x_3 = 1.3333333333333333, x_4 = 0.5


4. Дана система линейных уравнений, заданная расширенной матрицей:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найдите соотношение между параметрами $a$, $b$ и $c$, при которых система считается несовместной.<br/>

Преобразуем исходную матрицу к ступенчатой форме:

$$
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}=>
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4-2*1 & 5-2*2 & 6-2*3\\ 
7-3*1 & 8-3*2 & 9-3*3
\end{matrix}\right|
\begin{matrix}
a\\ 
b-2a\\
c-3a
\end{matrix}
\end{pmatrix}=>
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
4 & 2 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-2a\\
c-3a
\end{matrix}
\end{pmatrix}=>
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-2a\\
c-3a-2b
\end{matrix}
\end{pmatrix}
$$

Получаем, что при таких $a, c, b$, что $c-3a-2b \ne 0$ СЛАУ является несовместной.

### Часть 2

1. Решите систему уравнений методом Крамера:

а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$<br/>

СЛАУ в матричной форме примет вид:
$$
\begin{pmatrix}
\left.\begin{matrix}
1 & -2 \\ 
3 & -4 
\end{matrix}\right|
\begin{matrix}
1\\ 
7
\end{matrix}
\end{pmatrix}
$$

$$detA=\begin{vmatrix}
1 & -2 \\ 
3 & -4
\end{vmatrix} =1*(-4)-3*(-2)=2 \ne 0
$$

$$detA_1=\begin{vmatrix}
1 & -2 \\ 
7 & -4
\end{vmatrix} =1*(-4)-7*(-2)=10
$$

$$detA_2=\begin{vmatrix}
1 & 1 \\ 
3 & 7
\end{vmatrix} =1*7-3*1=4
$$
Тогда
$$
\begin{cases}
x_1 = \frac{detA_1}{detA} \\
x_2 = \frac{detA_2}{detA}
\end{cases}=>
\begin{cases}
x_1 = 5 \\
x_2 = 2
\end{cases}
$$

In [9]:
A = np.array([[1, -2], [3, -4]])
b = np.array([[1, 7]])
print("Корни СЛАУ:", np.linalg.solve(A, b[0]))

Корни СЛАУ: [5. 2.]


б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$<br/>

Представим СЛАУ в матричной форме:
$$
\begin{pmatrix}
\left.\begin{matrix}
2 & -1 & 5 \\ 
1 & 1 & -3 \\ 
2 & 4 & 1
\end{matrix}\right|
\begin{matrix}
10 \\ 
-2 \\
1
\end{matrix}
\end{pmatrix}
$$

$$detB=\begin{vmatrix}
2 & -1 & 5 \\ 
1 & 1 & -3 \\ 
2 & 4 & 1
\end{vmatrix} = 2* \begin{vmatrix}
1 & -3 \\
4 & 1
\end{vmatrix} + \begin{vmatrix}
1 & -3 \\ 
2 & 1
\end{vmatrix} + 5*\begin{vmatrix}
1 & 1 \\ 
2 & 4
\end{vmatrix} = 2*(1-4*(-3))+1-2*(-3)+5*(1*4-2*1)=26+7+10=43
$$

$$detB_1=\begin{vmatrix}
10 & -1 & 5 \\ 
-2 & 1 & -3 \\ 
1 & 4 & 1
\end{vmatrix} = 10* \begin{vmatrix}
1 & -3 \\
4 & 1
\end{vmatrix} + \begin{vmatrix}
-2 & -3 \\ 
1 & 1
\end{vmatrix} + 5*\begin{vmatrix}
-2 & 1 \\ 
1 & 4
\end{vmatrix} = 10*(1+12)-2-(-3)+5*((-2)*4-1)=130+1-45=86
$$

$$detB_2=\begin{vmatrix}
2 & 10 & 5 \\ 
1 & -2 & -3 \\ 
2 & 1 & 1
\end{vmatrix} = 2* \begin{vmatrix}
-2 & -3 \\
1 & 1
\end{vmatrix} -10* \begin{vmatrix}
1 & -3 \\ 
2 & 1
\end{vmatrix} + 5*\begin{vmatrix}
1 & -2 \\ 
2 & 1
\end{vmatrix} = 2-10*(1-2*(-3))+5*(1-2*(-2))=2-70+25=-43
$$

$$detB_3=\begin{vmatrix}
2 & -1 & 10 \\ 
1 & 1 & -2 \\ 
2 & 4 & 1
\end{vmatrix} = 2* \begin{vmatrix}
1 & -2 \\
4 & 1
\end{vmatrix} + \begin{vmatrix}
1 & -2 \\ 
2 & 1
\end{vmatrix} + 10*\begin{vmatrix}
1 & 1 \\ 
2 & 4
\end{vmatrix} = 2*(1-4*(-2))+(1*1-2*(-2))+10*(4-2)=18+5+20=43
$$

Следовательно
$$
\begin{cases}
x_1 = \frac{detB_1}{detB} \\
x_2 = \frac{detB_2}{detB} \\
x_3 = \frac{detB_3}{detB}
\end{cases}=>
\begin{cases}
x_1 = 2 \\
x_2 = -1 \\
x_3 = 1
\end{cases}
$$

In [10]:
B = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([[10, -2, 1]])
print("Корни СЛАУ:", np.linalg.solve(B, b[0]))

Корни СЛАУ: [ 2. -1.  1.]


2*. Найдите $L$-матрицу $LU$-разложения для матрицы коэффициентов:

а) $\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$<br/>

Общий вид L-матрицы в данном случае:
$$ 
L=\begin{pmatrix}
1 & 0 & 0 \\ 
l_{21} & 1 & 0 \\ 
l_{31} & l_{32} & 1
\end{pmatrix}
$$

$$l_{21} = \frac{a_{21}}{a_{11}} = 2,\ l_{31} = \frac{a_{31}}{a_{11}} = 3 $$
$$ l_{32} = \frac{a_{32}-l_{31}*a_{12}}{a_{22}-l_{21}*a_{12}} = \frac{26-3*2}{9-2*2} = 4 $$

L-матрица в итоге примет следующий вид:
$$
L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}
$$

б) $\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$

Общий вид L-матрицы в данном случае:
$$ 
L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
l_{21} & 1 & 0 & 0\\ 
l_{31} & l_{32} & 1 & 0\\
l_{41} & l_{42} & l_{43} & 1
\end{pmatrix}
$$

$$l_{21} = \frac{a_{21}}{a_{11}} = 2,\ l_{31} = \frac{a_{31}}{a_{11}} = 3,\ l_{41} = \frac{a_{41}}{a_{11}} = 4 $$
$$l_{32} = \frac{a_{32}-l_{31}*a_{12}}{a_{22}-l_{21}*a_{12}} = \frac{18-3*1}{5-2*1} = 5 $$
$$l_{42} = \frac{a_{42}-l_{41}*a_{12}}{a_{22}-l_{21}*a_{12}} = \frac{22-4*1}{5-2*1} = 6 $$
$$l_{43} = \frac{a_{43}-l_{41}*a_{13}-l_{42}*(a_{23}-l_{21}*a_{13})}{a_{33}-l_{31}*a_{13}-l_{32}*(a_{23}-l_{21}*a_{13})} = \frac{53-4*2-6*(8-2*2)}{29-3*2-5*(8-2*2)} = 7 $$

L-матрица в итоге примет следующий вид:
$$ 
L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}
$$

3*. Решите систему линейных уравнений методом $LU$-разложения:

$$\begin{cases}
2x_1+x_2+3x_3=1 \\
11x_1+7x_2+5x_3=-6 \\
9x_1+8x_2+4x_3=-5
\end{cases}$$

$$\begin{cases}
2x_1+x_2+3x_3=1 \\
11x_1+7x_2+5x_3=-6 \\
9x_1+8x_2+4x_3=-5
\end{cases}<=>Ax=b<=>\begin{pmatrix}
\left.\begin{matrix}
2 & 1 & 3\\ 
11 & 7 & 5\\ 
9 & 8 & 4
\end{matrix}\right|
\begin{matrix}
1\\ 
-6\\
-5
\end{matrix}
\end{pmatrix}
$$

Представим матрицу коэффициентов $A$ в виде матричного произведения $LU$:

$$
U=\begin{pmatrix}
2 & 1 & 3\\ 
11-5.5*2 & 7-5.5*1 & 5-5.5*3\\ 
9-4.5*2 & 8-4.5*1 & 4-4.5*3
\end{pmatrix}=>\begin{pmatrix}
2 & 1 & 3\\ 
0 & 1.5 & -11.5\\ 
0 & 3.5-2.33*1.5 & -9.5-2.33*(-11.5)
\end{pmatrix}=>\begin{pmatrix}
2 & 1 & 3\\ 
0 & 1.5 & -11.5\\ 
0 & 0 & 17.33
\end{pmatrix}
$$

$$
L=\begin{pmatrix}
1 & 0 & 0 \\ 
5.5 & 1 & 0 \\ 
4.5 & 2.33 & 1
\end{pmatrix}
$$

Произведём замену выражения $LUx=b$ на $Ly=b$ и решим полученную систему:

$$
\begin{cases}
y_1=1 \\
5.5y_1+y_2=-6 \\
4.5y_1+2.33y_2+y_3=-5
\end{cases}=>\begin{cases}
y_1=1 \\
y_2=-11.5 \\
2.33y_2+y_3=-9.5
\end{cases}=>\begin{cases}
y_1=1 \\
y_2=-11.5 \\
y_3=-9.5-2.33*(-11.5)
\end{cases}=>\begin{cases}
y_1=1 \\
y_2=-11.5 \\
y_3=17.295
\end{cases}
$$

Выполним обратную подстановку $Ux=y$:

$$
\begin{cases}
2x_1 + x_2 + 3x_3 = 1 \\
1.5x_2 - 11.5x_3 = -11.5 \\
17.33x_3 = 17.295
\end{cases}=>\begin{cases}
2x_1 + x_2 + 3x_3 = 1 \\
1.5x_2 - 11.5x_3 = -11.5 \\
x_3 \approx 1
\end{cases}=>\begin{cases}
2x_1 + x_2 \approx -2 \\
1.5x_2 \approx 0 \\
x_3 \approx 1
\end{cases}=>\begin{cases}
x_1 \approx -1 \\
x_2 \approx 0 \\
x_3 \approx 1
\end{cases}
$$

In [11]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([[1, -6, -5]])
print("Корни СЛАУ:", [round(x, 3) for x in np.linalg.solve(A, b[0])])

Корни СЛАУ: [-1.0, 0.0, 1.0]


In [12]:
lu, piv = linalg.lu_factor(A)
x_list = linalg.lu_solve((lu, piv), b.T)
for ind, x in enumerate([round(x[0], 3) for x in x_list]):
    print(f"x_{ind+1} = {x}")

x_1 = -1.0
x_2 = 0.0
x_3 = 1.0


4*. Решите систему линейных уравнений методом Холецкого:

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

In [13]:
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b = np.array([[531, -460, 193]])
print(A, b.T, sep="\n\n")

[[ 81 -45  45]
 [-45  50 -15]
 [ 45 -15  38]]

[[ 531]
 [-460]
 [ 193]]


$$l_{11} =\sqrt{a_{11}} = \sqrt{81} = 9$$
$$l_{21} =\frac{a_{21}}{l_{11}} = \frac{-45}{9} = -5$$
$$l_{31} =\frac{a_{31}}{l_{11}} = \frac{45}{9} = 5$$
$$l_{11} =\sqrt{a_{11}} = \sqrt{81} = 9$$
$$l_{21} =\frac{a_{21}}{l_{11}} = \frac{-45}{9} = -5$$ 
$$l_{31} =\frac{a_{31}}{l_{11}} = \frac{45}{9} = 5$$
$$l_{22} = \sqrt{a_{22}-l_{21}^{2}} = \sqrt{50 - (-5)^2} = 5$$
$$l_{32} = \frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right) = \frac{1}{5}(-15 - (-5) * 5) = 2$$
$$l_{33} = \sqrt{a_{33}-l_{32}^{2}-l_{31}^{2}} = \sqrt{38 - 2^2 - 5^2} = 3$$

$$
L=\begin{pmatrix}
9 & 0 & 0 \\
-5 & 5 & 0 \\
5 & 2 & 3
\end{pmatrix}, \ 
L^T=\begin{pmatrix}
9 & -5 & 5 \\
0 & 5 & 2 \\
0 & 0 & 3
\end{pmatrix}$$

In [14]:
L = np.linalg.cholesky(A)
print(L, L.T, sep="\n\n")

[[ 9.  0.  0.]
 [-5.  5.  0.]
 [ 5.  2.  3.]]

[[ 9. -5.  5.]
 [ 0.  5.  2.]
 [ 0.  0.  3.]]


$Ly=b:$

$$
\begin{cases}
9y_1 = 531 \\
-5y_1 + 5y_2 = -460 \\
5y_1 + 2y_2 + 3y_3 = 193
\end{cases}=>\begin{cases}
y_1 = 59 \\
y_2 = -33 \\
y_3 = -12
\end{cases}
$$

$L^Tx=y:$

$$
\begin{cases}
9x_1 - 5x_2 + 5x_3 = 59 \\
5x_2 + 2x_3 = -33 \\
3x_3 = -12
\end{cases}=>\begin{cases}  
x_1 = 6 \\
x_2 = -5 \\
x_3 = -4
\end{cases}  
$$

In [15]:
print(f"Корни СЛАУ: {', '.join([f'x_{index+1} = {round(x, 3)}' for index, x in enumerate(np.linalg.solve(A, b[0]))])}")

Корни СЛАУ: x_1 = 6.0, x_2 = -5.0, x_3 = -4.0


5*. Напишите на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [16]:
def solve_by_Cramers_method(coef_matrix, dependent):    
    if len(coef_matrix) != sum([len(x[x != 0])!=0 for x in coef_matrix.T]):
        return "Формула Крамера применима когда число уравнений равно числу неизвестных."
    
    main_det = np.linalg.det(coef_matrix)
    
    if main_det == 0:
        return "Формула Крамера применима только для невырожденных систем уравнений."
        
    coef_matrix_copies = list()
    for i in range(len(coef_matrix)):
        det_i = coef_matrix.copy()
        det_i[:, i]= dependent
        coef_matrix_copies.append(det_i)
    
    all_dets = [np.linalg.det(m) for m in coef_matrix_copies]
    equation_roots = all_dets / main_det
    return equation_roots

In [17]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
b = np.array([4, 6, -12])
print(solve_by_Cramers_method(A, b))

Формула Крамера применима только для невырожденных систем уравнений.


In [18]:
B = np.array([[1, -2], [3, -4]])
b = np.array([[1, 7]])
print(solve_by_Cramers_method(B, b))

[5. 2.]


In [19]:
C = np.array([[1, 2, 5], [3, 1, -8]])
b = np.array([4, 6])
print(solve_by_Cramers_method(C, b))

Формула Крамера применима когда число уравнений равно числу неизвестных.


In [20]:
D = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([[10, -2, 1]])
print(solve_by_Cramers_method(D, b))

[ 2. -1.  1.]
